### ISSUE TITLE
bug: migration script fails with error "edc_business_partner_group" already exists after upgrade to 0.6.0 version 

### ISSUE THREAD

**Issue by suh-rao** [eclipse-tractusx/tractusx-edc#1082]
## Describe the bug

After upgrade to 0.6.0 version control-plane fails to run. 
Exception:
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V0_0_1__Init_BusinessGroup_Schema.sql failed
2024-02-27 10:04:02 ------------------------------------------------------
2024-02-27 10:04:02 SQL State  : 42P07
2024-02-27 10:04:02 Error Code : 0
2024-02-27 10:04:02 Message    : ERROR: relation "edc_business_partner_group" already exists
2024-02-27 10:04:02 Location   : org/eclipse/tractusx/edc/postgresql/migration/bpn/V0_0_1__Init_BusinessGroup_Schema.sql (/workspace/org/eclipse/tractusx/edc/postgresql/migration/bpn/V0_0_1__Init_BusinessGroup_Schema.sql)
2024-02-27 10:04:02 Line       : 15
2024-02-27 10:04:02 Statement  : --
2024-02-27 10:04:02 --  Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
2024-02-27 10:04:02 --
2024-02-27 10:04:02 --  This program and the accompanying materials are made available under the
2024-02-27 10:04:02 --  terms of the Apache License, Version 2.0 which is available at
2024-02-27 10:04:02 --  https://www.apache.org/licenses/LICENSE-2.0
2024-02-27 10:04:02 --
2024-02-27 10:04:02 --  SPDX-License-Identifier: Apache-2.0
2024-02-27 10:04:02 --
2024-02-27 10:04:02 --  Contributors:
2024-02-27 10:04:02 --        Bayerische Motoren Werke Aktiengesellschaft (BMW AG) - initial API and implementation
2024-02-27 10:04:02 --
2024-02-27 10:04:02 
2024-02-27 10:04:02 
2024-02-27 10:04:02 CREATE TABLE edc_business_partner_group
2024-02-27 10:04:02 (
2024-02-27 10:04:02     bpn    VARCHAR                 NOT NULL
2024-02-27 10:04:02         CONSTRAINT edc_business_partner_group_pk
2024-02-27 10:04:02             PRIMARY KEY,
2024-02-27 10:04:02     groups JSON DEFAULT '[]'::JSON NOT NULL
2024-02-27 10:04:02 )
2024-02-27 10:04:02 
2024-02-27 10:04:02     at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:252)
2024-02-27 10:04:02     at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:214)
2024-02-27 10:04:02     at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:133)
2024-02-27 10:04:02     at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:65)
2024-02-27 10:04:02     at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:57)
2024-02-27 10:04:02     at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
2024-02-27 10:04:02     at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:56)
2024-02-27 10:04:02     at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:374)
2024-02-27 10:04:02     ... 25 more
2024-02-27 10:04:02 Caused by: org.postgresql.util.PSQLException: ERROR: relation "edc_business_partner_group" already exists
2024-02-27 10:04:02     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2712)
2024-02-27 10:04:02     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2400)
2024-02-27 10:04:02     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:367)
2024-02-27 10:04:02     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
2024-02-27 10:04:02     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
2024-02-27 10:04:02     at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
2024-02-27 10:04:02     at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
2024-02-27 10:04:02     at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
2024-02-27 10:04:02     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:292)
2024-02-27 10:04:02     at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:210)
2024-02-27 10:04:02     at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:89)
2024-02-27 10:04:02     at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:206)
2024-02-27 10:04:02     ... 31 more

### To Reproduce

Upgrade to 0.6.0 version and try to make control-plane up and running.

### Expected behavior

Control plane up and running

### Screenshots/Error Messages
Exception:
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V0_0_1__Init_BusinessGroup_Schema.sql failed
2024-02-27 10:04:02 ------------------------------------------------------
2024-02-27 10:04:02 SQL State  : 42P07
2024-02-27 10:04:02 Error Code : 0
2024-02-27 10:04:02 Message    : ERROR: relation "edc_business_partner_group" already exists
2024-02-27 10:04:02 Location   : org/eclipse/tractusx/edc/postgresql/migration/bpn/V0_0_1__Init_BusinessGroup_Schema.sql (/workspace/org/eclipse/tractusx/edc/postgresql/migration/bpn/V0_0_1__Init_BusinessGroup_Schema.sql)
2024-02-27 10:04:02 Line       : 15
2024-02-27 10:04:02 Statement  : --
2024-02-27 10:04:02 --  Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
2024-02-27 10:04:02 --
2024-02-27 10:04:02 --  This program and the accompanying materials are made available under the
2024-02-27 10:04:02 --  terms of the Apache License, Version 2.0 which is available at
2024-02-27 10:04:02 --  https://www.apache.org/licenses/LICENSE-2.0
2024-02-27 10:04:02 --
2024-02-27 10:04:02 --  SPDX-License-Identifier: Apache-2.0
2024-02-27 10:04:02 --
2024-02-27 10:04:02 --  Contributors:
2024-02-27 10:04:02 --        Bayerische Motoren Werke Aktiengesellschaft (BMW AG) - initial API and implementation
2024-02-27 10:04:02 --
2024-02-27 10:04:02 
2024-02-27 10:04:02 
2024-02-27 10:04:02 CREATE TABLE edc_business_partner_group
2024-02-27 10:04:02 (
2024-02-27 10:04:02     bpn    VARCHAR                 NOT NULL
2024-02-27 10:04:02         CONSTRAINT edc_business_partner_group_pk
2024-02-27 10:04:02             PRIMARY KEY,
2024-02-27 10:04:02     groups JSON DEFAULT '[]'::JSON NOT NULL
2024-02-27 10:04:02 )
2024-02-27 10:04:02 
2024-02-27 10:04:02     at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:252)
2024-02-27 10:04:02     at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:214)
2024-02-27 10:04:02     at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:133)
2024-02-27 10:04:02     at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:65)
2024-02-27 10:04:02     at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:57)
2024-02-27 10:04:02     at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
2024-02-27 10:04:02     at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:56)
2024-02-27 10:04:02     at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:374)
2024-02-27 10:04:02     ... 25 more
2024-02-27 10:04:02 Caused by: org.postgresql.util.PSQLException: ERROR: relation "edc_business_partner_group" already exists
2024-02-27 10:04:02     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2712)
2024-02-27 10:04:02     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2400)
2024-02-27 10:04:02     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:367)
2024-02-27 10:04:02     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
2024-02-27 10:04:02     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
2024-02-27 10:04:02     at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
2024-02-27 10:04:02     at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
2024-02-27 10:04:02     at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
2024-02-27 10:04:02     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:292)
2024-02-27 10:04:02     at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:210)
2024-02-27 10:04:02     at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:89)
2024-02-27 10:04:02     at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:206)
2024-02-27 10:04:02     ... 31 more

## Possible Implementation

Issue is because before 0.6.0,  edc_business_partner_group table was in subsystem: businessgroup and after changes from commit
"ndr_brt 12/20/2023 9:55 AM feat: add migrations for the policy-monitor sql schema " it got changed to bpn and getDataSourceNameConfigurationKey also changed.
Because of this flywaydb tried to run migration script and creates edc_business_partner_group table. This gets failed since it was already exists.

**Comment by DErCouch** [comment]
A missing "CREATE TABLE IF NOT EXISTS edc_business_partner_group" in the migration should do the trick!

**Comment by suh-rao** [comment]
> A missing "CREATE TABLE IF NOT EXISTS edc_business_partner_group" in the migration should do the trick!

yes

**Comment by suh-rao** [comment]
> Hi @suh-rao
> 
> thanks for raising this, the proposed @DErCouch fix should be ok, in case PRs are welcome :)

On second thought, for new tenants (not migrated from 0.5.* or so) edc_business_partner_group table would created correctly from current script. For them if we make changes in same sql script then flywaydb will raise exception too for subsequent upgrade. Hence  maynot be good solution.

**Comment by DErCouch** [comment]
> Hi @suh-rao
> 
> thanks for raising this, the proposed @DErCouch fix should be ok, in case PRs are welcome :)

@wolf4ood PR will be provided 😄

**Comment by wolf4ood** [comment]
Probably we can just revert the subsystem to `businessgroup`

**Comment by DErCouch** [comment]
> Probably we can just revert the subsystem to `businessgroup`

For backwards compatibility this might be a good option to move it back to the `businessgroup` folder

**Comment by suh-rao** [comment]
> > Probably we can just revert the subsystem to `businessgroup`
> 
> For backwards compatibility this might be a good option to move it back to the `businessgroup` folder. Added the refactoring to the PR as well.

Changing it back also might be problem. Tenants which are using 0.6.0 are in "bpn" and changing back to "businessgroup" also results in same issue

**Comment by DErCouch** [comment]
> > > Probably we can just revert the subsystem to `businessgroup`
> > 
> > 
> > For backwards compatibility this might be a good option to move it back to the `businessgroup` folder. Added the refactoring to the PR as well.
> 
> Changing it back also might be problem. Tenants which are using 0.6.0 are in "bpn" and changing back to "businessgroup" also results in same issue

For keeping the already existing data it makes sense to keep the old subsystem name "businessgroup". If there was already data inside, the migration would fail in it actual state (cause db already exists). So renaming as it was before and fixing the migration should solve the problem.
