### ISSUE TITLE
 Unable to Retrieve Client Secret from HashiCorp Vault

### ISSUE THREAD

**Issue by amnaishaq** [eclipse-tractusx/tractusx-edc#1229]
## Description:
I am facing an issue with retrieving the client secret from HashiCorp Vault while running my Docker container. I have configured my application to read the secret from Vault, but it's unable to retrieve it, resulting in the error message 'Client secret could not be retrieved.'

## Steps to Reproduce:

Run the Docker container with the provided command:

```sh
docker run -p 8080:8080 -p 8383:8383 -p 8282:8282 -p 9090:9090 -p 9999:9999 -v \"$PWD/configuration.properties:/app/configuration.properties\" -v \"$PWD/logging.properties:/app/logging.properties\" -v \"$PWD/opentelemetry.properties:/app/opentelemetry.properties\" edc-controlplane-postgresql-hashicorp-vault:latest
```
## VersionEdc: 0.6.1
**Expected Behavior:**
"The application should be able to retrieve the client secret from HashiCorp Vault and use it for authentication."

**Actual Behavior:**
"The application fails to retrieve the client secret from Vault and throws the error 'Client secret could not be retrieved.'"

**Additional Information:**
- Operating System: Linux Ubuntu 20.04
- Docker Version: 20.10.5
- HashiCorp Vault Version: 1.7.3

**Application Configuration (configuration.properties):**
```properties
edc.vault.hashicorp.url=http://localhost:8200
edc.vault.hashicorp.token=123456789
edc.vault.hashicorp.secret=1vidip12366545fkodojvdknv=
edc.vault.hashicorp.secret_path=secret/data/var/lib/vault/data
edc.vault.hashicorp.secret_key=secret1

# Configuración de la base de datos PostgreSQL
database.url=jdbc:postgresql://localhost:5432/tractusx
database.username=amna
database.password=amna

# Configuración de OAuth2
tx.ssi.oauth.client.id=z3iwTVc4G3r1TXhGT4alg9lMsKR8ubWT
tx.ssi.oauth.client.secret=DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5
tx.ssi.oauth.client.secret.alias=DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5
tx.ssi.oauth.client.secret.id=DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5
tx.ssi.oauth.authorization.url=https://dev-qssiii8v6z2dvbe2.us.auth0.com
tx.ssi.oauth.token.url=https://dev-qssiii8v6z2dvbe2.us.auth0.com/oauth/token
edc.oauth.client.id=DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5

edc.oauth.token.url=https://dev-qssiii8v6z2dvbe2.us.auth0.com
edc.oauth.public.key.alias=DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5
edc.oauth.client.id=z3iwTVc4G3r1TXhGT4alg9lMsKR8ubWT
edc.oauth.private.key.alias=1vidip12366545fkodojvdknv=

#Logs 
Executing task: docker logs --tail 1000 -f 00ea3658f2bba0106c4138036f5850e59df8547efbed8c508043e076836bd894 

OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2024-04-16 09:57:40:550 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.32.0
INFO 2024-04-16T09:57:43.557485675 Initialized FS Configuration
WARNING 2024-04-16T09:57:43.573367701 The runtime is configured as an anonymous participant. DO NOT DO THIS IN PRODUCTION.
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
INFO 2024-04-16T09:57:44.115199936 Initialized Micrometer Metrics
INFO 2024-04-16T09:57:44.116862086 Initialized Boot Services
INFO 2024-04-16T09:57:44.380594089 Initialized Core Default Services
INFO 2024-04-16T09:57:44.543026507 HTTPS enforcement it not enabled, please enable it in a production environment
INFO 2024-04-16T09:57:44.564008199 HTTPS enforcement it not enabled, please enable it in a production environment
INFO 2024-04-16T09:57:44.580501262 Initialized Hashicorp Vault
INFO 2024-04-16T09:57:44.619413056 Initialized Core Services
WARNING 2024-04-16T09:57:44.629703977 Settings: No setting found for key 'edc.hostname'. Using default value 'localhost'
INFO 2024-04-16T09:57:44.652560981 Initialized JSON-LD Extension
WARNING 2024-04-16T09:57:44.872825405 Error caching context URL 'https://w3id.org/dspace/2024/1/context.json' for URI 'jar:file:/app/edc-controlplane.jar!/document/dspace.jsonld'. Subsequent attempts to expand this context URL may fail.
INFO 2024-04-16T09:57:44.878626742 Initialized Local Transaction
INFO 2024-04-16T09:57:44.878897033 Initialized SQL Core
INFO 2024-04-16T09:57:44.899060466 Initialized org.eclipse.edc.connector.store.sql.assetindex.SqlAssetIndexServiceExtension
INFO 2024-04-16T09:57:44.905934615 Initialized org.eclipse.edc.connector.store.sql.contractnegotiation.SqlContractNegotiationStoreExtension
INFO 2024-04-16T09:57:44.912073199 Initialized org.eclipse.edc.connector.store.sql.policydefinition.SqlPolicyStoreExtension
INFO 2024-04-16T09:57:44.913213105 Initialized Control Plane Default Services
INFO 2024-04-16T09:57:44.917614967 Initialized org.eclipse.edc.connector.store.sql.contractdefinition.SqlContractDefinitionStoreExtension
INFO 2024-04-16T09:57:44.918143992 Initialized org.eclipse.edc.connector.contract.ContractNegotiationDefaultServicesExtension
INFO 2024-04-16T09:57:45.090324707 Initialized Jetty Service
INFO 2024-04-16T09:57:45.099128946 Initialized Jersey Web Service
WARNING 2024-04-16T09:57:45.100824098 Settings for [web.http.protocol.path] and/or [web.http.protocol.path] were not provided. Using default value(s) instead.
INFO 2024-04-16T09:57:45.101120779 Protocol API will be available under port=8282, path=/api/v1/dsp
INFO 2024-04-16T09:57:45.131080169 Initialized Dataspace Protocol API Configuration Extension
INFO 2024-04-16T09:57:45.15297212 Initialized Contract Core
INFO 2024-04-16T09:57:45.154865982 Initialized Contract Negotiation command handlers
INFO 2024-04-16T09:57:45.160449793 Initialized org.eclipse.edc.connector.store.sql.transferprocess.SqlTransferProcessStoreExtension
INFO 2024-04-16T09:57:45.160871033 Initialized Transfer Process Default Services
INFO 2024-04-16T09:57:45.198333634 Initialized Transfer Core
INFO 2024-04-16T09:57:45.201312628 Initialized org.eclipse.edc.connector.transfer.TransferProcessCommandExtension
WARNING 2024-04-16T09:57:45.201860189 No 'name' setting in group edc.datasource.asset found, no schema migrations will run for subsystem asset
INFO 2024-04-16T09:57:45.202131577 Initialized Postgresql schema migration for subsystem asset
WARNING 2024-04-16T09:57:45.202402826 No 'name' setting in group edc.datasource.contractdefinition found, no schema migrations will run for subsystem contractdefinition
INFO 2024-04-16T09:57:45.202533398 Initialized Postgresql schema migration for subsystem contractdefinition
WARNING 2024-04-16T09:57:45.202754467 No 'name' setting in group edc.datasource.contractnegotiation found, no schema migrations will run for subsystem contractnegotiation
INFO 2024-04-16T09:57:45.202913339 Initialized Postgresql schema migration for subsystem contractnegotiation
WARNING 2024-04-16T09:57:45.203180566 No 'name' setting in group edc.datasource.policy found, no schema migrations will run for subsystem policy
INFO 2024-04-16T09:57:45.203297241 Initialized Postgresql schema migration for subsystem policy
WARNING 2024-04-16T09:57:45.20352073 No 'name' setting in group edc.datasource.policy-monitor found, no schema migrations will run for subsystem policy-monitor
INFO 2024-04-16T09:57:45.203622958 Initialized Postgresql schema migration for subsystem policy-monitor
WARNING 2024-04-16T09:57:45.203817363 No 'name' setting in group edc.datasource.transferprocess found, no schema migrations will run for subsystem transferprocess
INFO 2024-04-16T09:57:45.203907384 Initialized Postgresql schema migration for subsystem transferprocess
WARNING 2024-04-16T09:57:45.204116839 No 'name' setting in group edc.datasource.edr found, no schema migrations will run for subsystem edr
INFO 2024-04-16T09:57:45.204237554 Initialized Postgresql schema migration for subsystem edr
WARNING 2024-04-16T09:57:45.204452216 No 'name' setting in group edc.datasource.bpn found, no schema migrations will run for subsystem bpn
INFO 2024-04-16T09:57:45.204551014 Initialized Postgresql schema migration for subsystem bpn
INFO 2024-04-16T09:57:45.204852174 Initialized SQL Business Partner Store
INFO 2024-04-16T09:57:45.2081422 Initialized EDR Cache Core
INFO 2024-04-16T09:57:45.208559783 Initialized OAuth2 Client
INFO 2024-04-16T09:57:45.211205333 Initialized SSI MIW OAuth2 Client
[otel.javaagent 2024-04-16 09:57:46:246 +0000] [OkHttp http://localhost:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
[otel.javaagent 2024-04-16 09:57:51:252 +0000] [OkHttp http://localhost:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
[otel.javaagent 2024-04-16 09:57:56:256 +0000] [OkHttp http://localhost:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
DEBUG 2024-04-16T09:58:00.798942258 [Hashicorp Vault] Failed to resolve secret 'DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5': [Failed to get secret with reason: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8200]
SEVERE 2024-04-16T09:58:00.80331357 Error booting runtime: java.lang.reflect.InvocationTargetException
org.eclipse.edc.spi.system.injection.EdcInjectionException: java.lang.reflect.InvocationTargetException
        at org.eclipse.edc.spi.system.injection.ProviderMethod.invoke(ProviderMethod.java:66)
        at org.eclipse.edc.boot.system.injection.lifecycle.RegistrationPhase.invokeAndRegister(RegistrationPhase.java:51)
        at org.eclipse.edc.boot.system.injection.lifecycle.RegistrationPhase.lambda$invokeProviderMethods$0(RegistrationPhase.java:45)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at org.eclipse.edc.boot.system.injection.lifecycle.RegistrationPhase.invokeProviderMethods(RegistrationPhase.java:45)
        at org.eclipse.edc.boot.system.injection.lifecycle.ExtensionLifecycleManager.provide(ExtensionLifecycleManager.java:70)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at org.eclipse.edc.boot.system.ExtensionLoader.bootServiceExtensions(ExtensionLoader.java:67)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.bootExtensions(BaseRuntime.java:139)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:200)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:83)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:71)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.edc.spi.system.injection.ProviderMethod.invoke(ProviderMethod.java:61)
        ... 20 more
Caused by: java.lang.NullPointerException: Client secret could not be retrieved
        at java.base/java.util.Objects.requireNonNull(Unknown Source)
        at org.eclipse.tractusx.edc.iam.ssi.miw.SsiMiwOauth2ClientExtension.createConfiguration(SsiMiwOauth2ClientExtension.java:75)
        at org.eclipse.tractusx.edc.iam.ssi.miw.SsiMiwOauth2ClientExtension.oauth2Client(SsiMiwOauth2ClientExtension.java:67)
        ... 23 more
[otel.javaagent 2024-04-16 09:58:00:809 +0000] [OkHttp http://localhost:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by ndr-brt** [comment]
@amnaishaq thanks for reporting, please wrap the console output blocks with the triple tick (```) so they will become readable, and please specify the EDC version affected because I didn't find it.

**Comment by amnaishaq** [comment]
@ndr-brt  i've corrected the console output blocks with triple backticks for readability. Also, I also have included the EDC version.

**Comment by ndr-brt** [comment]
looking at this log line:
```
[Hashicorp Vault] Failed to resolve secret 'DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5': [Failed to get secret with reason: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8200]
```

seems that the connector is not able to connect with the vault. Did you set the networking correctly? it's very unlikely that the vault can be reached with a `localhost` hostname.

**Comment by amnaishaq** [comment]
@ndr-brt    I've been working on configuring Vault for several days now, but I'm still encountering an issue when trying to establish the connection. I've attached my current configuration file for you to review and see if there's anything I might be overlooking.

If you have some time, could you take a look at the configuration file and provide me with some guidance on how to solve this issue? I'm open to any suggestions or advice you may have to offer.

I would greatly appreciate it! This problem has been causing me a lot of frustration, and I'm eager to resolve it as soon as possible.

Thank you very much for your time and assistance. 

```
edc.vault.hashicorp.url=http://amna.arlabdevelopments.com:8200
edc.vault.hashicorp.token=123456789
edc.vault.hashicorp.secret=1vidip12366545fkodojvdknv=
edc.vault.hashicorp.secret_path=secret/data/var/lib/vault/data
edc.vault.hashicorp.secret_key=secret1



# Configuración de la base de datos PostgreSQL
database.url=jdbc:postgresql://amna.arlabdevelopments.com:5432/tractusx
database.username=amna
database.password=amna

# Configuración de OAuth2
tx.ssi.oauth.client.id=z3iwTVc4G3r1TXhGT4alg9lMsKR8ubWT
tx.ssi.oauth.client.secret=DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5
tx.ssi.oauth.client.secret.alias=DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5
tx.ssi.oauth.client.secret.id=DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5
tx.ssi.oauth.authorization.url=https://dev-qssiii8v6z2dvbe2.us.auth0.com
tx.ssi.oauth.token.url=https://dev-qssiii8v6z2dvbe2.us.auth0.com/oauth/token
edc.oauth.client.id=DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5



edc.oauth.token.url=https://dev-qssiii8v6z2dvbe2.us.auth0.com
edc.oauth.public.key.alias=DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5
edc.oauth.client.id=z3iwTVc4G3r1TXhGT4alg9lMsKR8ubWT
edc.oauth.private.key.alias=1vidip12366545fkodojvdknv=
´´´

**Comment by amnaishaq** [comment]
@ndr-brt Now I have the containers on the same network but it still gives me problems .
```
amna@amna:~/tractusX/tractusx-edc$ docker network inspect my-network        
[
    {
        "Name": "my-network",
        "Id": "9ef4b622029586837cb0b2b65019f798c112fa4c1febeecddc415655953a0930",
        "Created": "2024-04-17T07:50:06.117711004+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "23b41578efbedd120ca4d83128e3509f3acec1e91afa1301a06ceb00bf6de942": {
                "Name": "my-vault",
                "EndpointID": "c441245976d49e4b7951e26d6be941bcaf0f618bbbf187b5f16af75c488a6871",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "48f621da7fc831b5406ecf1b87428b3537387da08b0a620338833fdcf1e81102": {
                "Name": "mi_postgres",
                "EndpointID": "be85aba089e6316c4a564054bc54fc757fdffe3b10274426118e4aa9291d0445",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]

## Log
```amna@amna:~/tractusX/tractusx-edc$ docker run     -p 8080:8080     -p 8383:8383     -p 8282:8282     -p 9090:9090     -p 9999:9999     -v "$PWD/configuration.properties:/app/configuration.properties"     -v "$PWD/logging.properties:/app/logging.properties"     -v "$PWD/opentelemetry.properties:/app/opentelemetry.properties"          --network my-network  edc-controlplane-postgresql-hashicorp-vault:latest
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2024-04-17 09:36:07:060 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.32.0
INFO 2024-04-17T09:36:10.257897162 Initialized FS Configuration
WARNING 2024-04-17T09:36:10.300566881 The runtime is configured as an anonymous participant. DO NOT DO THIS IN PRODUCTION.
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
INFO 2024-04-17T09:36:10.904063877 Initialized Micrometer Metrics
INFO 2024-04-17T09:36:10.905317798 Initialized Boot Services
INFO 2024-04-17T09:36:11.160389969 Initialized Core Default Services
INFO 2024-04-17T09:36:11.337020136 HTTPS enforcement it not enabled, please enable it in a production environment
INFO 2024-04-17T09:36:11.361337067 HTTPS enforcement it not enabled, please enable it in a production environment
INFO 2024-04-17T09:36:11.379272915 Initialized Hashicorp Vault
INFO 2024-04-17T09:36:11.422516874 Initialized Core Services
WARNING 2024-04-17T09:36:11.432954167 Settings: No setting found for key 'edc.hostname'. Using default value 'localhost'
INFO 2024-04-17T09:36:11.459866072 Initialized JSON-LD Extension
WARNING 2024-04-17T09:36:11.649361764 Error caching context URL 'https://w3id.org/dspace/2024/1/context.json' for URI 'jar:file:/app/edc-controlplane.jar!/document/dspace.jsonld'. Subsequent attempts to expand this context URL may fail.
INFO 2024-04-17T09:36:11.681192798 Initialized Local Transaction
INFO 2024-04-17T09:36:11.681620872 Initialized SQL Core
INFO 2024-04-17T09:36:11.698856783 Initialized org.eclipse.edc.connector.store.sql.assetindex.SqlAssetIndexServiceExtension
INFO 2024-04-17T09:36:11.708536535 Initialized org.eclipse.edc.connector.store.sql.contractnegotiation.SqlContractNegotiationStoreExtension
INFO 2024-04-17T09:36:11.743184652 Initialized org.eclipse.edc.connector.store.sql.policydefinition.SqlPolicyStoreExtension
INFO 2024-04-17T09:36:11.745665475 Initialized Control Plane Default Services
INFO 2024-04-17T09:36:11.751645548 Initialized org.eclipse.edc.connector.store.sql.contractdefinition.SqlContractDefinitionStoreExtension
INFO 2024-04-17T09:36:11.75609214 Initialized org.eclipse.edc.connector.contract.ContractNegotiationDefaultServicesExtension
INFO 2024-04-17T09:36:11.929261379 Initialized Jetty Service
INFO 2024-04-17T09:36:11.937775837 Initialized Jersey Web Service
WARNING 2024-04-17T09:36:11.940403796 Settings for [web.http.protocol.path] and/or [web.http.protocol.path] were not provided. Using default value(s) instead.
INFO 2024-04-17T09:36:11.941080159 Protocol API will be available under port=8282, path=/api/v1/dsp
INFO 2024-04-17T09:36:11.973194594 Initialized Dataspace Protocol API Configuration Extension
INFO 2024-04-17T09:36:12.003082178 Initialized Contract Core
INFO 2024-04-17T09:36:12.00548817 Initialized Contract Negotiation command handlers
INFO 2024-04-17T09:36:12.01268624 Initialized org.eclipse.edc.connector.store.sql.transferprocess.SqlTransferProcessStoreExtension
INFO 2024-04-17T09:36:12.013496172 Initialized Transfer Process Default Services
INFO 2024-04-17T09:36:12.060545045 Initialized Transfer Core
INFO 2024-04-17T09:36:12.064720045 Initialized org.eclipse.edc.connector.transfer.TransferProcessCommandExtension
WARNING 2024-04-17T09:36:12.065649804 No 'name' setting in group edc.datasource.asset found, no schema migrations will run for subsystem asset
INFO 2024-04-17T09:36:12.066298491 Initialized Postgresql schema migration for subsystem asset
WARNING 2024-04-17T09:36:12.066980292 No 'name' setting in group edc.datasource.contractdefinition found, no schema migrations will run for subsystem contractdefinition
INFO 2024-04-17T09:36:12.067316796 Initialized Postgresql schema migration for subsystem contractdefinition
WARNING 2024-04-17T09:36:12.067875083 No 'name' setting in group edc.datasource.contractnegotiation found, no schema migrations will run for subsystem contractnegotiation
INFO 2024-04-17T09:36:12.06817495 Initialized Postgresql schema migration for subsystem contractnegotiation
WARNING 2024-04-17T09:36:12.068697521 No 'name' setting in group edc.datasource.policy found, no schema migrations will run for subsystem policy
INFO 2024-04-17T09:36:12.068984543 Initialized Postgresql schema migration for subsystem policy
WARNING 2024-04-17T09:36:12.069444982 No 'name' setting in group edc.datasource.policy-monitor found, no schema migrations will run for subsystem policy-monitor
INFO 2024-04-17T09:36:12.069775438 Initialized Postgresql schema migration for subsystem policy-monitor
WARNING 2024-04-17T09:36:12.070249678 No 'name' setting in group edc.datasource.transferprocess found, no schema migrations will run for subsystem transferprocess
INFO 2024-04-17T09:36:12.070553504 Initialized Postgresql schema migration for subsystem transferprocess
WARNING 2024-04-17T09:36:12.071036991 No 'name' setting in group edc.datasource.edr found, no schema migrations will run for subsystem edr
INFO 2024-04-17T09:36:12.071362191 Initialized Postgresql schema migration for subsystem edr
WARNING 2024-04-17T09:36:12.071807671 No 'name' setting in group edc.datasource.bpn found, no schema migrations will run for subsystem bpn
INFO 2024-04-17T09:36:12.072124796 Initialized Postgresql schema migration for subsystem bpn
INFO 2024-04-17T09:36:12.072675635 Initialized SQL Business Partner Store
INFO 2024-04-17T09:36:12.076809968 Initialized EDR Cache Core
INFO 2024-04-17T09:36:12.077659146 Initialized OAuth2 Client
INFO 2024-04-17T09:36:12.081069794 Initialized SSI MIW OAuth2 Client
[otel.javaagent 2024-04-17 09:36:12:912 +0000] [OkHttp http://localhost:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
[otel.javaagent 2024-04-17 09:36:17:917 +0000] [OkHttp http://localhost:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
[otel.javaagent 2024-04-17 09:36:22:920 +0000] [OkHttp http://localhost:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
DEBUG 2024-04-17T09:36:27.682138724 [Hashicorp Vault] Failed to resolve secret 'DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5': [Failed to get secret with reason: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8200]
SEVERE 2024-04-17T09:36:27.685336897 Error booting runtime: java.lang.reflect.InvocationTargetException
org.eclipse.edc.spi.system.injection.EdcInjectionException: java.lang.reflect.InvocationTargetException
        at org.eclipse.edc.spi.system.injection.ProviderMethod.invoke(ProviderMethod.java:66)
        at org.eclipse.edc.boot.system.injection.lifecycle.RegistrationPhase.invokeAndRegister(RegistrationPhase.java:51)
        at org.eclipse.edc.boot.system.injection.lifecycle.RegistrationPhase.lambda$invokeProviderMethods$0(RegistrationPhase.java:45)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at org.eclipse.edc.boot.system.injection.lifecycle.RegistrationPhase.invokeProviderMethods(RegistrationPhase.java:45)
        at org.eclipse.edc.boot.system.injection.lifecycle.ExtensionLifecycleManager.provide(ExtensionLifecycleManager.java:70)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at org.eclipse.edc.boot.system.ExtensionLoader.bootServiceExtensions(ExtensionLoader.java:67)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.bootExtensions(BaseRuntime.java:139)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:200)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:83)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:71)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.edc.spi.system.injection.ProviderMethod.invoke(ProviderMethod.java:61)
        ... 20 more
Caused by: java.lang.NullPointerException: Client secret could not be retrieved
        at java.base/java.util.Objects.requireNonNull(Unknown Source)
        at org.eclipse.tractusx.edc.iam.ssi.miw.SsiMiwOauth2ClientExtension.createConfiguration(SsiMiwOauth2ClientExtension.java:75)
        at org.eclipse.tractusx.edc.iam.ssi.miw.SsiMiwOauth2ClientExtension.oauth2Client(SsiMiwOauth2ClientExtension.java:67)
        ... 23 more
[otel.javaagent 2024-04-17 09:36:27:695 +0000] [OkHttp http://localhost:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317

**Comment by ndr-brt** [comment]
looking at this line:
```
DEBUG 2024-04-17T09:36:27.682138724 [Hashicorp Vault] Failed to resolve secret 'DUzJHQTnIHFUsCp5QXvk3BPXtSq1S-xVIF4FO1eFqI9eQjFB9XdCEEebyxfCt3V5': [Failed to get secret with reason: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8200]
```

it tells that the hashicorp vault has been configured with the `localhost` address, that represent a local address.

In any case this is definitely not an issue with the EDC but it is a docker issue, I cannot help you on this, sorry.

**Comment by rs7oh7** [comment]
if you are running your vault in your local machine, try replacing `localhost:8200` with `host.docker.internal:8200`

**Comment by rs7oh7** [comment]
replace `localhost:8200` with `host.docker.internal:8200` . this should work for containers connecting to services running in host machine.

**Comment by amnaishaq** [comment]
@cipherscribe7  Thank you!!
Now it's giving me this error all the time and I don't know how to fix it.

```
Caused by: java.lang.NullPointerException: Client secret could not be retrieved
        at java.base/java.util.Objects.requireNonNull(Unknown Source)
        at org.eclipse.tractusx.edc.iam.ssi.miw.SsiMiwOauth2ClientExtension.createConfiguration(SsiMiwOauth2ClientExtension.java:75)
     [otel.javaagent 2024-04-18 07:54:01:946 +0000] [OkHttp http://localhost:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
