### ISSUE TITLE
Object has already been returned to this pool or is invalid

### ISSUE THREAD

**Issue by tuncaytunc-zf** [eclipse-tractusx/tractusx-edc#180]
## Describe the bug
In `edc-controlplane-postgresql` an exception occurs during startup

Reported in [Jira](https://jira.catena-x.net/browse/A1IDSC-482)

### To Reproduce
On startup from controlplane when you use the image `edc-controlplane-postgresql`

### Screenshots/Error Messages
```
SEVERE 2023-04-05T08:06:08.375372 StateMachineManager [transfer-process] error caught
java.lang.IllegalStateException: Object has already been returned to this pool or is invalid
    at org.apache.commons.pool2.impl.BaseGenericObjectPool.markReturningState(BaseGenericObjectPool.java:1251)
    at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:1029)
    at org.eclipse.edc.sql.pool.commons.CommonsConnectionPool.returnConnection(CommonsConnectionPool.java:76)
    at org.eclipse.edc.sql.datasource.PooledDataSourceConnection.close(PooledDataSourceConnection.java:96)
    at org.eclipse.edc.connector.store.sql.transferprocess.store.SqlTransferProcessStore.lambda$nextForState$1(SqlTransferProcessStore.java:80)
    at org.eclipse.edc.transaction.spi.NoopTransactionContext.execute(NoopTransactionContext.java:34)
    at org.eclipse.edc.connector.store.sql.transferprocess.store.SqlTransferProcessStore.nextForState(SqlTransferProcessStore.java:69)
    at org.eclipse.edc.connector.transfer.process.TransferProcessManagerImpl.lambda$processTransfersInState$21(TransferProcessManagerImpl.java:591)
    at org.eclipse.edc.statemachine.StateProcessorImpl.process(StateProcessorImpl.java:46)
    at java.base/java.util.stream.ReferencePipeline$5$1.accept(Unknown Source)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.base/java.util.stream.LongPipeline.reduce(Unknown Source)
    at java.base/java.util.stream.LongPipeline.sum(Unknown Source)
    at org.eclipse.edc.statemachine.StateMachineManager.performLogic(StateMachineManager.java:118)
    at org.eclipse.edc.statemachine.StateMachineManager.lambda$loop$2(StateMachineManager.java:106)
    at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
    at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:160)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by florianrusch-zf** [comment]
Can you please improve the issue with some more details? With the current content, we won't know what the problem was in a year. Also the full stack trace would be helpful.

**Comment by tuncaytunc-zf** [comment]
> Can you please improve the issue with some more details? With the current content, we won't know what the problem was in a year. Also the full stack trace would be helpful.

Hi @florianrusch-zf I have added the whole stack trace and linked the Jira ticket. I hope this helps people to understand it better after one year :smile:
